### PR TITLE
Update launch.sh

### PR DESCRIPTION
**Pull request by jarriztg**

### CODE REVIEW

**Comment by BH-YAGHI** [comment]
nice'

**Comment by RememberTheAir** [comment]
I'm not an expert in bash... what this script should do, with sreen program?

**Comment by jarriztg** [comment]
Keep the bot running without any time offset

**Comment by jarriztg** [comment]
You can close launch.sh and the bot will run yum

**Comment by BH-YAGHI** [comment]
@jarriztg  this need to "screen bash steady.sh -s"

**Comment by BH-YAGHI** [comment]
@jarriztg  this need to "screen bash steady.sh -s"

**Comment by jarriztg** [comment]
Not, this only take a screen in bot.lua and the screen will set a name to keep session

**Comment by jarriztg** [comment]
Test it

**Comment by RememberTheAir** [comment]
I'll try it as soon as I can, in this days I'm a bit afk :)

**Pull request closed without merging**
