### PR TITLE
add function to make subprocess

### PR DESCRIPTION
**Pull request by otgo**

### CODE REVIEW

**Comment by RememberTheAir** [comment]
Uhm

How should this be used in Group Butler? 🤔

**Comment by otgo** [comment]
yeah, i know 10 persons using that, i taught them that function and they are happy.

Example without use that function in any large process:

```Lua
-- Making request but the api is slowly <--- 1-2 minute(s) (bot waiting)
-- Downloading... <- 1-2 minute(s) (bot waiting)
-- Updaling... <--- 1 - 2 minutes in any file large. (bot waiting)
----- totally = 3-6 minutes and the bot stopped ---
```


With that function:
```Lua
-- Making request but the api is slowly <--- 1-2 minute(s)  <--- bot yet running -> child process
-- Downloading... <- 1-2 minute(s) (bot waiting) <--- bot yet running -> child process
-- Updaling... <--- 1 - 2 minutes in any file large. <--- bot yet running -> child process
----- totally = 3-6 minutes and the bot running ---
```

**Comment by NotAFile** [comment]
Wouldn't it be wise to just put that into your local forks then instead of here? I have not read all of the code but I don't think GB would benefit from it now.

**Comment by RememberTheAir** [comment]
I agree with what @NotAFile said, at the moment Group Butler doesn't perform "heavy" operations that could force the bot to wait for their end, such as downloading/uploading a big file, or dealing with API slowdowns

**Pull request closed without merging**
