### PR TITLE
add Name format in /unban

### PR DESCRIPTION
**Pull request by Legendary007**

### CODE REVIEW

**Comment by RememberTheAir** [comment]
It should be something like "User %s unbanned by %s"

**Comment by Legendary007** [comment]
Fixed :+1:

**Comment by RememberTheAir** [comment]
I'll merge this as soon as I have some time to merge and update the translations files, or users who are not using the default language will get an error when unbanning people. Because the second argument of `format` doesn't have its placeholder `%s`

Thanks :+1:

**Comment by mymedia2** [comment]
No, they won't have to get an error, because Gettext will return this string not modifying (unless, of course, fuzzy translations are disabled)

**Comment by RememberTheAir** [comment]
Oh, true

**Comment by kamikazechaser** [comment]
@mymedia2 Good inference

**Pull request merged**
