### PR TITLE
Fix most luacheck warnings and make the bot more modular

### PR DESCRIPTION
**Pull request by yangm97**
From 1335 warnings to 11, I think that’s a pretty good start 😁

Overview:
- Change `dkjson` back to `lua-cjson`
- Renamed `lua/bot.lua` to `lua/main.lua`
- Moved polling logic from `lua/main.lua` to `polling.lua`
- The only remaining global variable is `bot` (already added to .luacheckrc globals), mostly to keep the admin commands $init and $stats working. Could easily avoid that by using a module instead.

Things to look after:
- I did my best while fixing “line is too long” warnings but some strings might need to be readjusted. Using a short id (instead of the english string) in source code would be a better IMHO
- `$init` doesn’t seem to be reloading the modules, possibly due to the fact none of them are global anymore. I think it may be better to replace it with something like `$stop` and rely on the supervisor (docker, systemd, `launch.sh`…) to relaunch 
- This builds on top of the previous docker PR. Simply merging this should be enough to close both PRs

### CODE REVIEW

**Comment by yangm97** [comment]
Hold on, trow away variable `_` is conflicting with localisation variable `_`. Don’t merge until the name of the latter is changed to `i18n` or something.

**Comment by yangm97** [comment]
Fixed. Should be ready to go now.

**Comment by Synk0** [comment]
What is the status of this?

**Comment by NotAFile** [comment]
> until the name of the latter is changed to i18n or something

This breaks the translation unfortunately. Gettext relies on scanning the file for _(...) to find translatable strings. You can change this prefix, but it has to be consistent for the collection to work.

**Comment by yangm97** [comment]
Which file need to be changed?

**Comment by NotAFile** [comment]
Well, everything. The "localisation variable" needs to be the same everywhere. We could rename it to something like _T(...) or whatever, but it needs to be the same everywhere

**Comment by yangm97** [comment]
@NotAFile well, I’ve picked up i18n() as the localisation variable and used it everywhere (on the lua side of things)

**Comment by yangm97** [comment]
I’m not sure what’s needed to do on the gettext script though, in fact I even forgot it existed.

**Pull request merged**
