### PR TITLE
don't edit msg to link

### PR DESCRIPTION
**Pull request by Behrooz-Yaghi**

### CODE REVIEW

**Comment by RememberTheAir** [comment]
`msg.edited` is a boolean and you can't `string.lower()` it.
I can't understand the purpose of this pull request, `text_lower` should countain the text of a message/edited message.

You are placing a boolean in it, also this won't never happen because if `msg.edited` is `true`, msg.text can't be `false`/`nil`.

I closed this pull for now, if you want you can explain me here the meaning of that modification because I feel as I'm missing something

**Comment by Behrooz-Yaghi** [comment]
no idea for this! your right, `msg.edited` cant `string.lower()` :(

**Comment by Behrooz-Yaghi** [comment]
@RememberTheAir see this:

`if msg.edited then
			local edited_lower = msg.edited:lower()
			if edited_lower:match('telegram%.me') or edited_lower:match('telegram%.dog') then
				msg.spam = 'links'
			end
		end`
i think its ok now.

**Comment by RememberTheAir** [comment]
You are still trying to lowering a boolean.

Look at [this line](https://github.com/RememberTheAir/GroupButler/blob/master/bot.lua#L228)

> `update.edited_message.edited = true`

And at [this line](https://github.com/RememberTheAir/GroupButler/blob/master/bot.lua#L234)

> `msg = update.message or update.edited_message`

**Comment by Behrooz-Yaghi** [comment]
i think its your work, because i write (edited.msg with link) is `onmessage.lua` with `edited.msg:find` and i dont work with this.

*I can't understand the purpose of this pull request*:
now you can understand it maybe anamnesis for make this method for group_bulter

and very sorry for this pulllllllll.

**Comment by Behrooz-Yaghi** [comment]
@RememberTheAir 👍 

```bash
  	links = msg.text or msg.edited
    if links:find('[Hh][Tt][Tt][Pp][Ss][:][/][/]')
		or links:find('[Hh][Tt][Tt][Pp][Ss][:][/][/]')
		or links:find('[Tt][Ee][Ll][Ee][Gg][Rr][Aa][Mm].[Mm][Ee][/]')
		or links:find('[Ww][Ww][Ww][.]')
		or links:find('[.][Cc][Oo][Mm]') then 
        local ads_status = (db:hget('chat:'..msg.chat.id..':char', 'Ads')) or 'allowed'
        if ads_status == 'kick' or ads_status == 'ban' then
    	    if not roles.is_admin_cached(msg) then
    	        local name = misc.getname_final(msg.from)
    	        local res
    	        if ads_status == 'kick' then
    	            res = api.kickUser(msg.chat.id, msg.from.id)
    	        elseif ads_status == 'ban' then
    	            res = api.banUser(msg.chat.id, msg.from.id, msg.normal_group)
    	        end
            	if not misc.is_silentmode_on(msg.chat.id) then
    	        if res then
    	            misc.saveBan(msg.from.id, 'ads') --save ban
    	            local message = _("%s *kicked* ⛔️\n ads message not allowed here ❗️"):format(name)
    	            if ads_status == 'ban' then
						message = _("%s *banned* ⛔️\n ads message not allowed here ❗️"):format(name)
    	            end
    	            api.sendMessage(msg.chat.id, message, true)
    	         end
            end
         end
      end
	end
```

**Comment by RememberTheAir** [comment]
1. `msg.edited` is a boolean (**!!!**), you can't give to `links` a boolean value if you need to use a function from the `string` library on it
2. No need to search for links in the msg text: Telegram already told us if a message contains a link. In the `entities` field, more info [here](https://core.telegram.org/bots/api#messageentity). And this is exactly [what the bot checks](https://github.com/RememberTheAir/GroupButler/blob/master/bot.lua#L332) every time a message has an `entities` field
3. `Ads` field doesn't exist in the database (**??**), and if the intention was to add a new field (even if we already have `link` and `tglink`), it must be added under the `chat_settings` in `config.lua`, because that table it's what the bot uses to build its keyboards.

The rest is ok, but I still have the felling I didn't get you.
Where should this code be placed, in your idea?

**Pull request closed without merging**
