### PR TITLE
Ability to change language

### PR DESCRIPTION
**Pull request by BH-YAGHI**
user can set bot lang to desired lang.

### CODE REVIEW

**Comment by RememberTheAir** [comment]
This is not how it should work. Each "[new language] has been set" should be translated in its `.po` file.

Anyway, I don't merge one-line pull requests from people who go around saying I've copied his bot, or pretending to be me.

**Comment by BH-YAGHI** [comment]
u are 100% moron

**Comment by RememberTheAir** [comment]
Okey

**Comment by BH-YAGHI** [comment]
The source must Be easily (Lightweight and comfortable) to this **[gettext]** There's a lot of overtime!
11 lang pack and all source edited 
**Whereas previously they were all in one place!**
Your destroyed the old (easy) source. I did not expect you 👎

**Comment by RememberTheAir** [comment]
You destroyed it. You are the developer, right? Aren't you Riccardo?

**Comment by BH-YAGHI** [comment]
@RememberTheAir   iam sorry for you.
this 2 screen shots is Fake you can ask of @SaeedRahmani66 
They were my enemy and Had tried to destroy my Credit!
i only have 1 account in Telegram and my account UserName is @BehroozYaghi my account is dont delete (What at this time or in the future)
but the my fake account is deleted so its not me.
i dont know who say you iam Riccardo but you should now if you dont know its me(screen shots) so Should not play with my reputation. 
i say everywhere my bot base in your bot 
Even you can ask of iranian user what i say to the https://telegram.me/NOD32Team/2496
no reason i say iam Riccardo!
**iam  very very sorry for your Children reaction.**

**Comment by BH-YAGHI** [comment]
@RememberTheAir   iam sorry for you.
this 2 screen shots is Fake you can ask of @SaeedRahmani66 
They were my enemy and Had tried to destroy my Credit!
i only have 1 account in Telegram and my account UserName is @BehroozYaghi my account is dont delete (What at this time or in the future)
but the my fake account is deleted so its not me.
i dont know who say you iam Riccardo but you should now if you dont know its me(screen shots) so Should not play with my reputation. 
i say everywhere my bot base in your bot 
Even you can ask of iranian user what i say to the https://telegram.me/NOD32Team/2496
no reason i say iam Riccardo!
**iam  very very sorry for your Children reaction.**

**Comment by RememberTheAir** [comment]
lel

**Comment by kamikazechaser** [comment]
R.I.P English

**Comment by BH-YAGHI** [comment]
@kamikazechaser Hi voyeur 😄

**Pull request closed without merging**
