### PR TITLE
Update antispam.lua

### PR DESCRIPTION
**Pull request by peyman2afm**

### CODE REVIEW

**Comment by peyman2afm** [comment]
Sorry.. I wanted pull request in beta branches but I made a mistake.

**Comment by kamikazechaser** [comment]
@peyman2afm Looks ok to me.

**Comment by mymedia2** [comment]
I think it's better to make these labels as `emoji action`. For example `<boot> kick` or `<hammer> ban`. They have to begin with a lowercase letter like button in the anti-flood menu. Then they will identically look and they will be automatically translated.

tmp_20747-screenshot_2016-11-28-01-26-41-316912141

**Comment by mymedia2** [comment]
also @RememberTheAir, why do you still use an emoji with a lock in the main menu?

tmp_20747-screenshot_2016-11-28-01-27-20792931568

**Comment by RememberTheAir** [comment]
@peyman2afm I agree with @mymedia2, can you make those "`K`" and "`B`" lowercase?

@mymedia2 about emojis, yes, they're old, I'll change them

**Comment by peyman2afm** [comment]
@RememberTheAir okay I've send new pull request and change some things

**Pull request closed without merging**
