### PR TITLE
Launch.sh using tmux now

### PR DESCRIPTION
**Pull request by jarriztg**
./launch.sh - start a normal session.
./launch.sh tmux - start a session with tmux.
./launch.sh kill - kill the session in tmux
./launch.sh attach- see the errors in the tmux console (attach)

### CODE REVIEW

**Comment by BH-YAGHI** [comment]
@jarriztg  no need for that.

only can use "sudo nohup bash ./launch.sh" for stay bot

**Comment by TiagoDanin** [comment]
**Tmux** has a best managing

**Comment by jarriztg** [comment]
@BH-YAGHI yep, but tmux its great in bash

**Comment by jarriztg** [comment]
no problem xd pr closed.

**Pull request closed without merging**
