### PR TITLE
Improvements And Hotfixes

### PR DESCRIPTION
**Pull request by kamikazechaser**
These changes are to improve the bots features in general:

1. Improved REGEX for more intense Telegram link detection.

### CODE REVIEW

**Comment by TiagoDanin** [comment]
Recommend this pattern: `string.match(string.lower(msg.text), "(telegram.%w%w%w?[/ ])")` ;)

image

**Comment by kamikazechaser** [comment]
That would also detect telegram.org and telegram blog posts. So if someone linked a useful article on the blog or say, a bot API method for reference purposes he would get warned/kicked.

**Comment by kamikazechaser** [comment]
Actually you just reminded me to review my pattern to prevent the above!

**Comment by kamikazechaser** [comment]
image 001 12 25

Does this affect the PR?

**Comment by RememberTheAir** [comment]
Ew. This probably happens because I deleted some commits yesterday, now the pull request includes all the changes that have been deleted, even if they've been restored

**Comment by kamikazechaser** [comment]
Ok. So I better close this PR and get a fresh fork!

**Comment by kamikazechaser** [comment]
Closing PR and restarting due to commits mixup

**Pull request closed without merging**
