### PR TITLE
Translation Arabic

### PR DESCRIPTION
**Pull request by jaksz**
Please check if everything that I translated so far works, especially since this is a right-to-left language (while the variables are left-to-right). We might be in for a wild ride 😆.

### CODE REVIEW

**Comment by RememberTheAir** [comment]
Sorry for the late reply, and thanks a lot for the translation!

Actually I'm a bit busy this week and I have few time to make a pull and sync the repo with also local unstaged things, but I'll try to give it a ride as soon as I can :)

**Comment by jaksz** [comment]
@RememberTheAir, the Arabic translation is now complete and can be merged!

**Comment by RememberTheAir** [comment]
Thanks! You sure all the fileds are filled? :)

**Comment by RememberTheAir** [comment]
If it's all ok, I'll update it this evening

**Comment by jaksz** [comment]
Yes, I double-checked and all the fields are filled!

**Comment by RememberTheAir** [comment]
@jaksz Awesome!

**Comment by RememberTheAir** [comment]
Okey merged, got some merging errors but I've solved by typing random git commands in the console. I hope it's all ok, now I'll add some other things with the next commit, then I'll update the actual bot

**Pull request merged**
