### PR TITLE
WIP: Persist data to Postgres, add multi threading support and move from polling to webhook and more

### PR DESCRIPTION
**Pull request by yangm97**
🚨 **DO NOT MERGE YET!** 🚨

# Contributing
Send pull requests to https://gitlab.com/Synko/GroupButler in order to have this PR updated.

# Persist data to Postgres
Although redis is still used for temporary data, persistent data is now stored in Postgres. 
The old schema, although it could be easily ported to mongo, would still be inefficient because it used to workaround the fact redis is not relational (like storing the same data multiple times but in different keys). Still, all database operations are wrapped inside dedicated functions for each table. Should there be any schema change, database software change, etc. GroupButler should be (mostly) database agnostic. 

# Add multi threading support and move from polling to webhook
Thanks to the power of openresty and some nice non-blocking libraries, GroupButler can be 100% non-blocking and load balanced from CPU cores to multiple servers. This offers great speed and stability improvements, along with reduced unexpected downtimes. 
It also allows people building on top of GroupButler to “fool” GB with fake requisitions for debugging or route telegram requests as they come along. For instance, you can manually send fake updates using curl; have a “router” that allows choosing between beta and stable versions (from the same bot @username). The possibilities are endless!

# More
Some refactoring and code cleanup were made.

### CODE REVIEW

**Comment by NotAFile** [comment]
Whoa, this is great stuff! Many things, many of them overdue.

This pull request is giant though, perhaps it would have been better to incrementally merge features and wait for any issues to appear. I feel some decisions could have been discussed more. I personally wouldn't feel comfortable just placing this many new features in production at @groupbutlerbot just like that, but @remembertheair will have to weigh in on that.

I'd think it would be better to `cherry-pick` these commits and then merge the features individually.

What is the data migration strategy?

-1 on `i18n.lua`. Gettext is a tried and true format, with well maintained implementations for every language and widely used. It is supported by most translation tools and has a consistent workflow across projects. `i18n` is a side project of some person who made something and uploaded it to github. There are no tools that support it, it is probably not well tested and people need to learn lua to translate.

**Comment by mymedia2** [comment]
Hello! Thank you for your huge work.

I'm in general agreement with the previous commentator. But let me say a word or two about i18n and l10n.

The special editors facilitate translating, because an English variant and a translatable one are on the same screen. And translation memory is also available.

And yet I think translations for each language have to be in separate files. It makes team work easier.

**Comment by yangm97** [comment]
About i18n, I’m not happy with that either (you can see there aren’t many commits bringing translations back). It doesn’t support weekdays, months, etc. I would be more than happy to use something else. I have to admit I don’t have much experience with PO itself, so it could be just that the way it was implemented in GB to be the issue.

> And yet I think translations for each language have to be in separate files. It makes team work easier.

It can be done with i18n too. I just thought having separate files per plugin would make more sense, to anyone building on top of GB, for instance.

About discussing, I agree too. It just happens there’s no “development” group to discuss these things and I didn’t want to flood the repo with issues. So I thought it would be better to come up with my half finished ideas in the form of a PR. 

For cherry picking, my first attempt was to have different branches for each feature, turns out they kind overlapped so I just merged them all into master. I was also having issues with space/tab inconsistency, which made merging a nightmare (thus why I end up adding an .editorconfig).

**Comment by yangm97** [comment]
Forgot do mention: logs can now be handled just like nginx logs (with log levels and everything). Since telegram isn’t meant to be a log aggregation tool, I would suggest redirecting the log into one. 
This and webhooks should make debbugging beta/prod problems way easier.

Oh, and the bot won’t \*ever\* shutdown because of an error due to the way openresty was designed.

**Comment by NotAFile** [comment]
I've had a look at many commits and I think we need to do some cleanup work. Many commits changing white-space for no reason, bad commit messages, commiting conflicts etc.

I've started cherry-picking the most important features, but there's a few things I disagree with. One of those things is removing real support for installing and running without docker, `i18n.lua` and the general structural changes.

Here's what I think we should do:

- [x] cherry pick editorconfig commit
- [ ] cherry pick and squash reading from ENV commits in a backwards-compatible way
- [ ] change docs to recommend environment variables
- [ ] add webhook option and deploy and test that with the main GroupButler
- [ ] migrate data to postgres
- [ ] switch persistent data to postgres
- [ ] make redis optional

**Comment by yangm97** [comment]
> Cleanup work

This is the second item in todo:

- [ ] make it work
- [ ] make it right
- [ ] make it fast

> One of those things is removing real support for installing and running without docker

This is part of the WIP phase. I want to make sure to document both install methods, for now I just removed the older script because it wouldn’t work as expected.

> Many commits changing white-space for no reason

Like I said, the project had mixed usage of spaces and tabs, so I began converting them following .editorconfig rules as I discovered inconsistencies. If there’s a tool to automate the process…

> and the general structural changes.

What did you not like? Lua files were moved to a lua directory and not much was changed since then. This directory structure follows what you would expect from an openresty application.

**Comment by yangm97** [comment]
Re-adding polling support should be as easy as dofile init.lua and dofile handler inside the the getupdates loop, along with minor changes.

Bear in mind this is WIP, so I would ask to focus the discussion on added/changed stuff, nothing was intended to be removed as far as I remember.

**Comment by yangm97** [comment]
Also laid ground for fixing #85 by adding `lastmsg` column to `chat_users` table.

**Comment by RememberTheAir** [comment]
That's huge. Thanks @yangm97 for your work.

Looks like I got to look at how all the things you added work, since I've never worked with most of them, so for now I cannot comment on them.

But I generally agree with what @NotAFile and @mymedia2 said about gettext and `i18n`, mainly because there are no tools that support it.

>I'd think it would be better to cherry-pick these commits and then merge the features individually.

I agree with that, but as @yangm97 said things may overlap each other, no?

> If there’s a tool to automate the process…

@mymedia2 opened #139 that I haven't been able to merge because of conflicts (eh), aimed to fix tabs/spaces inconsistency

> It just happens there’s no “development” group to discuss these things

I guess it's time to open one (?)

_PS, I haven't been able to dig in the changes yet. So I haven't a clean idea of all the things that changed_

**Comment by yangm97** [comment]
Removed the bit about changing the localisation system, will be breaking all of this into smaller PRs.

**Comment by yangm97** [comment]
I’m going to close this as we are merging this gradually.

**Pull request closed without merging**
