### PR TITLE
Now people can clone new branches

### PR DESCRIPTION
**Pull request by peyman2afm**

### CODE REVIEW

**Comment by peyman2afm** [comment]
Sorry for bad English...

**Comment by RememberTheAir** [comment]
I was thinking to something else....

If you want you can open another pull request into the beta branch and edit the install script to clone the right branch (and also the manual installation intructions in the readme).

Something like:
```bash
#  install.sh

...

echo -e "\e[1;36mFetching latest Group Butler source code\e[0m"
git clone -b beta https://github.com/RememberTheAir/GroupButler.git

...
```

(and same goes for the instructions in the readme)

**Comment by RememberTheAir** [comment]
@peyman2afm Look at what can I do from here

**Comment by peyman2afm** [comment]
Sorry I don't know how to change install.sh but thank you.

**Pull request closed without merging**
