### PR TITLE
Second review

### PR DESCRIPTION
**Pull request by caiodias**
Fixed more typos

### CODE REVIEW

**Comment by XENONIUM** [comment]
Mute

сб, 23 июля 2016 г., 9:33 Caio Dias <notifications@github.com>:

**Comment by RememberTheAir** [comment]
@caiodias can you take a look to this pulll request? With the last update some thing changed, if you get rid of unexisting strings, I can merge it asap

**Comment by caiodias** [comment]
Sure, I will try to do that on this weekend. Probably tomorrow

**Comment by RememberTheAir** [comment]
Awesome! Take your time, no hurry

**Comment by caiodias** [comment]
New Pull Request created https://github.com/RememberTheAir/GroupButler/pull/48 (maybe because I'm idiot and wasn't able enough to update this one, or not) :)

**Pull request closed without merging**
