### PR TITLE
Updated ru.po

### PR DESCRIPTION
**Pull request by feUStBWxmxiCUSwGPgTNoqZN3ydPi2qp**

### CODE REVIEW

**Comment by feUStBWxmxiCUSwGPgTNoqZN3ydPi2qp** [comment]
Updated ru.po

**Comment by RememberTheAir** [comment]
Thanks. I will update the locale file on the bots as soon as I'm done with the new `deleteMessage`-related functions I've been working on the past days.

**Comment by anupritaisno1** [comment]
@RememberTheAir Don't think about asking for help in implementing

**Comment by anupritaisno1** [comment]
@anupritaisno1 Yes but I'm telling you because you need to know

**Comment by RememberTheAir** [comment]
@anupritaisno1 are you ok?

**Comment by anupritaisno1** [comment]
I have no clue. I definitely don't remember writing that

**Comment by RememberTheAir** [comment]
[@githubbot](https://t.me/githubbot) messing up I guess

**Pull request merged**
