### PR TITLE
Games as new type of media

### PR DESCRIPTION
**Pull request by mymedia2**
I used yet undocumented features so this code will be able to become nonworking.

Also I made next changes:
 * Second parameter of sendStartMe function was removed
 * Notifications in dashboard were added for translation
 * changeFloodSettings was moved from utilities.lua into floodmanager.lua
 * Some unused code was deleted in floodmanager
 * Detection of group language was fixed in dashboard
 * Information about reports was added in dashboard

### CODE REVIEW

**Comment by mymedia2** [comment]
It works!  :smile:
[How it works](http://hostingkartinok.com/show-image.php?id=ca9818c23242af83e58e8c9088bce4d4)

**Comment by Benjarobbi** [comment]
Wow! Nice :)

**Comment by Benjarobbi** [comment]
👍👍

**Comment by kamikazechaser** [comment]
This is awesome

**Comment by Benjarobbi** [comment]
True :)

Am 03.10.2016 11:02 schrieb "Mohammed Sohail" <notifications@github.com>:

**Pull request merged**
